doc: init iclocale documentation
image-charts/documentation pull request #24
Opened 2020-09-03 14:44 UTC by AugustinRibreau

2020-09-04 15:14 UTC, FGRibreau requested changes

2020-09-04 15:14 UTC, FGRibreau commented on docs/reference/iclocale
> +!!! info "Enterprise+ subscription only"
erreur dans l'extension de fichier

2020-09-04 15:14 UTC, FGRibreau commented on docs/reference/iclocale
> +    iclocale support is only enabled in **Enterprise+** subscriptions
"iclocale" décrire ce qu'est "iclocale", se mettre dans la peau de quelqu'un qui n'a jamais entendu parlé de ça

2020-09-04 15:14 UTC, FGRibreau commented on docs/reference/iclocale
> +#### iclocale
décrire ce que c'est fonctionnellement, avant d'en parler en terme technique

2020-09-04 15:14 UTC, FGRibreau commented on docs/reference/iclocale
> +iclocale is an option that refers to location. The purpose of this option is to define a location for the graphic.
iclocale => `iclocale`

2020-09-04 15:14 UTC, FGRibreau commented on docs/reference/iclocale
> +iclocale is an option that refers to location. The purpose of this option is to define a location for the graphic.
> Some charts might be rendered for customers over various location with different currency and localization requirements. `iclocale` is a query parameter to specify in what localization the chart should be rendered

2020-09-04 15:14 UTC, FGRibreau commented on docs/reference/iclocale
> +In order to choose the location, Image-Charts sets up iclocale. To activate it just add the parameter `iclocale=fr/en/de/...`.
à enlever

2020-09-04 15:14 UTC, FGRibreau commented on docs/reference/iclocale
> +- **`<iclocale_activation>`** set to `fr`, `de`, `en`... to activate iclocale mode and locate the chart.
- est-ce un enum ?  si oui, donner toutes les valeurs de l'enum 

> Allowed values are: `fr', `de', `de`

2020-09-04 15:14 UTC, FGRibreau commented on docs/reference/iclocale
> +![chart](https://image-charts.com/chart?chd=s%3AAtheresadifferencebetweenknowingthepathandwalkingthepath&chf=b0%2Clg%2C90%2C03a9f4%2C0%2C3f51b5%2C1&chs=700x200&cht=bvs&chxt=y&icac=fgribreau&iclocale=
les deux exemples ne changent rien entre iclocale=en et iclocale=fr.

Astuce: regarde les tests unitaires pour découvrir comment cela fonctionne et des exemples qui parleront au lecteur.

Objectif : la documentation doit montrer tous les impacts que peut avoir `iclocale` sur le graphique (currency & gestion des number separators de mémoire)

2020-09-04 15:14 UTC, FGRibreau commented on mkdocs.yml
> +      - Iclocale support: reference/iclocale.md
- je ne pense pas que ça pouvais compiler, vu que le nom de fichier ne se termine pas par .md
- `Iclocale support` ne veut rien dire pour le lecteur "Language localisation" serait plus adéquate (learn: https://fr.wikipedia.org/wiki/Localisation_(linguistique) )

2020-09-07 10:53 UTC, FGRibreau commented on docs/reference/iclocale
> +    iclocale support is only enabled in **Enterprise+** subscriptions
@AugustinRibreau c'est toujours pas corrigé

2020-09-07 10:53 UTC, FGRibreau commented on docs/reference/iclocale
> +#### iclocale
@AugustinRibreau c'est toujours pas corrigé

2020-09-07 10:54 UTC, FGRibreau commented on docs/reference/iclocale
> +iclocale is an option that refers to location. The purpose of this option is to define a location for the graphic.
@AugustinRibreau c'est toujours pas corrigé

2020-09-07 10:54 UTC, FGRibreau commented on docs/reference/iclocale
> +- **`<iclocale_activation>`** set to `fr`, `de`, `en`... to activate iclocale mode and locate the chart.
@AugustinRibreau c'est toujours pas corrigé

2020-09-07 10:54 UTC, FGRibreau commented on docs/reference/iclocale
> +![chart](https://image-charts.com/chart?chd=s%3AAtheresadifferencebetweenknowingthepathandwalkingthepath&chf=b0%2Clg%2C90%2C03a9f4%2C0%2C3f51b5%2C1&chs=700x200&cht=bvs&chxt=y&icac=fgribreau&iclocale=
@AugustinRibreau c'est toujours pas corrigé

2020-09-08 08:33 UTC, AugustinRibreau commented
@FGRibreau j'ai fais les modifications

2020-09-08 19:28 UTC, FGRibreau commented on docs/reference/iclocale.md
> +#### Iclocale
@AugustinRibreau

2020-09-08 19:28 UTC, FGRibreau commented on docs/reference/iclocale.md
> +    Iclocale support is only enabled in **Enterprise** subscriptions
@AugustinRibreau

2020-09-15 22:13 UTC, merged